### ISSUE TITLE
Win32-EventLog input throwing "LoadError: no such file to load -- jruby-win32ole" (

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-eventlog#5] opened 2015-02-07 00:10 UTC
From https://logstash.jira.com/browse/LOGSTASH-2227

My conf is about as simple as it gets:

{code}
input {
  eventlog {
    type  => 'Win32-EventLog'
  }
}

output {
  stdout {}
}
{code}

Here's the output:

{code}
Using milestone 2 input plugin 'eventlog'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones {:level=>:warn}
LoadError: no such file to load -- jruby-win32ole
       require at org/jruby/RubyKernel.java:1085
       require at file:/C:/TransCore/elasticsearch_poc/logstash-1.4.1/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
       require at file:/C:/TransCore/elasticsearch_poc/logstash-1.4.1/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
       require at c:/TransCore/elasticsearch_poc/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
      register at c:/TransCore/elasticsearch_poc/logstash-1.4.1/lib/logstash/inputs/eventlog.rb:36
  start_inputs at c:/TransCore/elasticsearch_poc/logstash-1.4.1/lib/logstash/pipeline.rb:135
          each at org/jruby/RubyArray.java:1613
  start_inputs at c:/TransCore/elasticsearch_poc/logstash-1.4.1/lib/logstash/pipeline.rb:134
           run at c:/TransCore/elasticsearch_poc/logstash-1.4.1/lib/logstash/pipeline.rb:72
       execute at c:/TransCore/elasticsearch_poc/logstash-1.4.1/lib/logstash/agent.rb:139
           run at c:\TransCore\elasticsearch_poc\logstash-1.4.1\lib\logstash\runner.rb:168
          call at org/jruby/RubyProc.java:271
    initialize at c:/TransCore/elasticsearch_poc/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/task.rb:12
{code}

I've seen the same behavior on Win 7 Pro and Win Server 2008 R2.

**Comment by wiibaa** [comment] 2015-02-07 12:40
@suyograo this is fixed in 1.5 as this dependency is explicited in the plugin gemspec https://github.com/logstash-plugins/logstash-input-eventlog/blob/master/logstash-input-eventlog.gemspec#L29. 
The root cause was that during the split between logstash and logstash-contrib for 1.4.0, jruby-win32ole was removed from the logstash core gemspec due to different windows inputs being moved to contrib (wmi...) while eventlog remained in core...
That's why installing contrib was identified as a workaround...

**Comment by suyograo** [comment] 2015-02-07 20:10
@wiibaa thanks for pointing that out.

**Closed** 2015-02-07 20:10 UTC
